# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 306770ea1316c4708d1d84c7a3092012b76d6dacbc4be801646df3209a8d4335aa31fdfe16305330b6ade7c63d6c05608947c778c29730c95b404635b87652f0

test:
  secret_key_base: f4df167bc9fa2d20f2adb2cd3146792ce52debff84e111e1e818958d63b4dff32e67bfdc9e3f6ef9dae2d8cef49d9300e78fa9edb511adf19135b7ce834eeb9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
